name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  AZURE_CONTAINER_REGISTRY: $
  AZURE_APP_SERVICE_NAME: $
  AZURE_RESOURCE_GROUP: $
  IMAGE_NAME: chat-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: $

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: $
          username: $
          password: $

      - name: Build and push Docker image
        run: |
          cd src/
          docker build -t $/$:latest .
          docker push $/$:latest
